version: '3.8'
name: ternovs-app
services:
  frontend:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.local
      args:
        - USER
        - UID
        - GID
    restart: unless-stopped
    volumes:
      - ./src:/srv/frontend
  nginx:
    image: nginx:1.20.2
    env_file: .env
    restart: on-failure:10
    volumes:
      - ./docker/local/nginx/site.conf:/etc/nginx/conf.d/site.conf:ro
    ports:
      - "80:80"
