FROM node:14.18.1-alpine3.14

#FROM node:16.16.0-alpine3.16

ARG USER=node
ARG UID=1000
ARG GID=1000

USER root
RUN mkdir -p /var/www/html/frontend

RUN apk add --update supervisor curl yarn

COPY docker/config/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

RUN chown -R ${UID}:${GID} /var/www/html/frontend \
    && chmod -R 775 /var/www/html/frontend \
    && chown -R ${UID}:${GID} /run

# Switch to use a non-root user from here on
USER ${UID}:${GID}

WORKDIR /var/www/html/frontend

CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
